"""CASCADE DELETE on submission

Revision ID: 54d9cfe74362
Revises: 132f51734616
Create Date: 2025-11-22 23:17:17.572232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54d9cfe74362'
down_revision: Union[str, Sequence[str], None] = '132f51734616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('submission_team_id_fkey'), 'submission', type_='foreignkey')
    op.drop_constraint(op.f('submission_question_id_fkey'), 'submission', type_='foreignkey')
    op.create_foreign_key(None, 'submission', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submission', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key(op.f('submission_question_id_fkey'), 'submission', 'question', ['question_id'], ['id'])
    op.create_foreign_key(op.f('submission_team_id_fkey'), 'submission', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
