"""Add admin column to team table

Revision ID: c2f40405b103
Revises: 598fdd03f7d7
Create Date: 2025-11-20 19:43:29.142975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2f40405b103'
down_revision: Union[str, Sequence[str], None] = '598fdd03f7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'admin')
    # ### end Alembic commands ###
