"""Add accuracy to question

Revision ID: dbb90e86e357
Revises: 54d9cfe74362
Create Date: 2025-11-26 14:59:58.073951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbb90e86e357'
down_revision: Union[str, Sequence[str], None] = '54d9cfe74362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('accuracy', sa.Integer(), nullable=False, server_default="10"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'accuracy')
    # ### end Alembic commands ###
